services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64}
      # - RABBITMQ_URI=${RABBITMQ_URI} # URI untuk koneksi ke RabbitMQ
    depends_on:
      - mongo
      # - rabbitmq # Tambahkan dependensi ke RabbitMQ
    restart: unless-stopped
    networks:
      - fintrack-net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - fintrack-net

  # rabbitmq: # Tambahkan service baru untuk RabbitMQ
  #   image: rabbitmq:3.13-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672" # Port untuk aplikasi
  #     - "15672:15672" # Port untuk UI Management
  #   networks:
  #     - fintrack-net

volumes:
  mongo_data:
    driver: local

networks:
  fintrack-net:
    driver: bridge
