services:
  app:
    build: .
    container_name: node_app
    ports:
      # Memetakan port eksternal 4000 ke port internal 4000
      - "3000:3000"
    environment:
      # Langsung mengatur PORT di sini untuk konsistensi
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64}
    depends_on:
      - mongo
    restart: unless-stopped # Tambahan: Otomatis restart jika kontainer berhenti
    networks:
      - fintrack-net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped # Tambahan: Otomatis restart jika kontainer berhenti
    networks:
      - fintrack-net

volumes:
  mongo_data:
    driver: local

networks:
  fintrack-net:
    driver: bridge
